config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :insts do
    resources :comments
    post :confirm, on: :collection
  end
  
  resources :pictures, only: [:index, :edit, :destroy, :update]

  root 'top#index'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :inst
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # Instをパラメータの値から探し出し,Instに紐づくcommentsとしてbuildします。
    @comment = current_user.comments.build(comment_params)
    @inst = @comment.inst
    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @comment.save
        format.html { redirect_to inst_path(@inst), notice: 'コメントを投稿しました。' }
      else
        format.html { render :new }
      end
    end
  end
  
  def destroy
    set_comment
    @inst = @comment.inst
    respond_to do |format|
      @comment.destroy
        format.html { redirect_to inst_path(@inst) }
          flash.now[:notice] = "コメントが削除されました!"
        format.js { render :index }
    end
  end
  
  private
    # ストロングパラメーター
    def comment_params
      params.require(:comment).permit(:inst_id, :content)
    end
    
    def set_comment
       @comment = Comment.find(params[:id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([inst, comment], remote: true) do |f| %>
  <%= f.hidden_field :inst_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', edit_inst_comment_path(inst, comment), class: "fa fa-pencil-square-o fa-lg" %>
            <%= link_to '', inst_comment_path(inst, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.inst.comments, inst: @comment.inst }) %>")
$(':text').val('')