config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :insts do
    resources :comments
    post :confirm, on: :collection
  end
  
  resources :pictures, only: [:index, :edit, :destroy, :update]

  root 'top#index'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    def index
      @pictures = Inst.all
    end
    
    def destroy
      @picture = Inst.find(params[:id])
      @picture.image=nil
      if @picture.save
       redirect_to pictures_path, notice: "画像を削除しました"
      else
       redirect_to pictures_path, notice: "画像が削除できませんでした"          
      end
    end
    
    def edit
      @picture = Inst.find(params[:id])
    end
    
    def update
      @picture = Inst.find(params[:id])
      @picture.update(pictures_params)
      goindex
    end
    
    private
        def goindex
            redirect_to pictures_path
        end
        
        def pictures_params
            params.require(:picture).permit(:image)
        end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/edit.html.erb
<%= form_for(@picture) do |f| %>
  
  <%= f.label :画像 %>
  <%= f.file_field :image %>
  <br>
  <%= f.submit %>
  <br>
<% end %>
<%= link_to "画像一覧へ", pictures_path %>

app/views/pictures/index.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <p><%= notice %></p>
    <br>
    
    <h1><strong>画像一覧</strong></h1>
    <%= link_to "アウスタ一覧へ",  insts_path,  class: 'btn btn-default btn-sm btn-info'%>

    <% @pictures.each do |picture| %>
      <p><h3><%=picture.title%></h3></p>
      <br>
      <p><%= image_tag(picture.image) %></p>
      <br>
      <%= link_to "画像を編集する", edit_picture_path(picture.id), class: 'btn btn-default btn-sm btn-primary' %>
      <%= link_to '画像を削除する', picture_path(picture.id),  method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    
    <% end %>
  </div>
</div>