config/routes.rb
Rails.application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :insts do
    resources :comments
    post :confirm, on: :collection
  end
  
  resources :pictures, only: [:index, :edit, :destroy, :update]

  root 'top#index'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  

end

app/models/inst.rb
class Inst < ActiveRecord::Base
    belongs_to :user
    # CommentモデルのAssociationを設定
    has_many :comments, dependent: :destroy
    
    validates :title, presence: true
    mount_uploader :image, ImageUploader
end

app/controllers/insts_controller.rb
class InstsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_inst, only: [:show, :edit, :update, :destroy]
  
  def index
    @insts = Inst.all
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def new
    @inst = Inst.new
  end
  
  def show
    @comment = @inst.comments.build
    @comments = @inst.comments
  end
  
  def create
    @inst = Inst.new(insts_params)
    @inst.user_id = current_user.id
    
    if @inst.save
      NoticeMailer.sendmail_inst(@inst).deliver
      redirect_to insts_path, notice: "新しい投稿がされました"
    else
      redirect_to new_inst_path, notice: "タイトルを入力してください"
    end
  end
  
  def destroy
    @inst.destroy
    redirect_to insts_path
  end
  
  def edit
  end
  
  def update
    @inst.update(insts_params)
    redirect_to insts_path
  end
  
  private
    def insts_params
      params.require(:inst).permit(:title, :content, :image)
    end
    
    def set_inst
      @inst = Inst.find(params[:id])
    end
end

app/helpers/insts_helper.rb
module InstsHelper
end

app/views/insts/edit.html.erb
<div class="container">
  <div class="col-md-2 col-md-offset-3 col-sm-11 ">
  <br>
  <%= link_to "アウスタの一覧へ", insts_path, class: 'btn btn-default btn-sm btn-info' %>
  <br>
<%= form_for(@inst) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.label :画像 %>
  <%= f.file_field :image %>
  <br>
  <%= f.submit %>
<% end %>


  </div>
</div<

app/views/insts/index.html.erb
<div class="container-fluid">
  <div class="col-md-offset-2 col-md-8 col-md-offset-2 col-sm-11">
    <p><%= notice %></p>
    <br>
    <div class ="intro">
      <%= link_to "投稿",  new_inst_path,  class: 'btn btn-default btn-sm btn-primary'%>
      <%= link_to "画像一覧",  pictures_path,  class: 'btn btn-default btn-sm btn-primary'%>
      <br><br>
  
      <% @insts.each do |inst| %>
        <div class="panel panel-primary">  
        
          <div class="panel-heading">
             <%= link_to inst_path(inst) do %>
              <h4><strong><%= inst.title %></strong></h4> 
            <% end %>
            written by <%=  User.find(inst.user_id).name %> <%= profile_img(User.find(inst.user_id)) %> 
          </div>
          
          <div class="panel-body">
            <p><%= inst.content %></p>
            <p><%= image_tag(inst.image) %></p>
          </div>
          
          <div class="panel-footer">
           <%= link_to "編集する", edit_inst_path(inst.id), class: 'btn btn-default btn-sm btn-primary' %>
            <%= link_to '削除する', inst_path(inst.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/insts/new.html.erb
<div class="container">
  <div class="col-md-2 col-md-offset-3 col-sm-11 ">
<p><%= notice %></p>
<br>
  <%= link_to "一覧へ", insts_path, class: 'btn btn-default btn-sm btn-primary' %>
  <%= form_for(@inst) do |f| %>
    <%= f.label :タイトル %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :内容 %>
    <%= f.text_field :content %>
    <br>
    <%= f.label :画像選択 %>
    <%= f.file_field :image %>
    <br>
    <div><%= f.submit %></div>
  <% end %>
  
  </div>
</div>

app/views/insts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="inst-text">
      <p class="left"><strong>タイトル</strong></p>
      <p class="left"><%= @inst.title %></p>
      <p class="left"><strong>内容</strong></p>
      <p class="left"><%= @inst.content %></p>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @inst.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, inst: @inst } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, inst: @inst } %>
    <% if current_user.id == @inst.user_id %>
      <%= link_to '編集', edit_inst_path(@inst) %> |
    <% end %>
    <%= link_to '戻る', insts_path %>
  </div>
</div>